// Generates protocol/test-vectors/reach-ik.json: a Noise IK run with Reach's prologue and
// realistic payloads, in the same format as the official cacophony vectors. The C# test
// suite replays it to prove both implementations produce identical bytes.
// Run (from protocol/ts): npm run vectors
import { writeFileSync } from 'node:fs';
import { IKHandshake, keyPairFromSecret } from '../src/noise';

const hex = (b: Uint8Array) => Buffer.from(b).toString('hex');
const utf8 = (s: string) => new TextEncoder().encode(s);
const fixedKey = (fill: number) => new Uint8Array(32).fill(fill);

const prologue = utf8('reach/1');
const phoneStatic = keyPairFromSecret(fixedKey(1));
const phoneEphemeral = keyPairFromSecret(fixedKey(2));
const pcStatic = keyPairFromSecret(fixedKey(3));
const pcEphemeral = keyPairFromSecret(fixedKey(4));

const payloads = [
  '{"pairCode":"AAECAwQFBgcICQoLDA0ODw"}',
  '{}',
  '{"type":"hello","deviceName":"iPhone","appVersion":"1.0.0"}',
  '{"type":"welcome","pcName":"DESKTOP-PC","agentVersion":"1.0.0"}',
  '{"type":"key.text","text":"مرحبا 👋"}',
  '{"type":"term.output","data":"\\u001b[32mPS C:\\\\Users> \\u001b[0m"}',
].map(utf8);

const initiator = new IKHandshake({ initiator: true, prologue, s: phoneStatic, e: phoneEphemeral, rs: pcStatic.publicKey });
const responder = new IKHandshake({ initiator: false, prologue, s: pcStatic, e: pcEphemeral });

const messages: { payload: string; ciphertext: string }[] = [];
const c0 = initiator.writeMessage(payloads[0]);
responder.readMessage(c0);
messages.push({ payload: hex(payloads[0]), ciphertext: hex(c0) });
const c1 = responder.writeMessage(payloads[1]);
initiator.readMessage(c1);
messages.push({ payload: hex(payloads[1]), ciphertext: hex(c1) });

const it = initiator.split();
const rt = responder.split();
payloads.slice(2).forEach((payload, i) => {
  const sender = i % 2 === 0 ? it : rt;
  messages.push({ payload: hex(payload), ciphertext: hex(sender.encrypt(payload)) });
});

const vector = {
  protocol_name: 'Noise_IK_25519_ChaChaPoly_SHA256',
  init_prologue: hex(prologue),
  init_static: hex(phoneStatic.secretKey),
  init_ephemeral: hex(phoneEphemeral.secretKey),
  init_remote_static: hex(pcStatic.publicKey),
  resp_prologue: hex(prologue),
  resp_static: hex(pcStatic.secretKey),
  resp_ephemeral: hex(pcEphemeral.secretKey),
  handshake_hash: hex(initiator.handshakeHash),
  messages,
};

writeFileSync(process.argv[2], JSON.stringify({ source: 'generated by protocol/ts/scripts/generate-reach-vectors.ts', vectors: [vector] }, null, 2) + '\n');
